### ISSUE TITLE
 Simplify the check algorithm?

### ISSUE THREAD

**Issue by hhhxiao** [depressed-pho/slime-finder-pe#2]
```javascript
 let n   = mt.random_int();
 let m         = 0xcccccccd;
 let hi        = umul32_hi(n, m);
 let hi_shift3 = hi >>> 3;
 let res       = ((((hi_shift3 + (hi_shift3 * 4)) & 0xffffffff) * 2) & 0xffffffff) >>> 0;
 this._isSlimy = (n == res);
```
just replace this with `this._isSlimy = (n % 10 == 0)`

**Comment by depressed-pho** [comment]
I don't think that's a valid simplification. Did you confirm that the change still produces the same result?

**Comment by hhhxiao** [comment]
A few days ago, When I try to rewrite the alogrithm with C++, I  found the slime finder algorithm just is:
 1. get a hash value with  seed  =low_32_bit(x*0x1f1f1f1f)^z
 2. get the frist random number with mt algorithm:  n  = mt19937(seed);
 3. check if n % 10 == 0
  here I test this with ts:
```javascript
function isSlimy(x_uint, z_uint) {
    var seed = umul32_lo(x_uint, 0x1f1f1f1f) ^ z_uint;
    var mt = new MersenneTwister(seed);
    var n = mt.random_int();
    var m = 0xcccccccd;
    var hi = umul32_hi(n, m);
    var hi_shift3 = hi >>> 3;
    var res = ((((hi_shift3 + (hi_shift3 * 4)) & 0xffffffff) * 2) & 0xffffffff) >>> 0;
    return (n == res);
}
function isSlimy2(x_uint, z_uint) {
    var seed = umul32_lo(x_uint, 0x1f1f1f1f) ^ z_uint;
    var mt = new MersenneTwister(seed);
    var n = mt.random_int();
    return (n %10 == 0);
}

for(var i  = -1000;i < 1000;i++){
    for(var j = -10 ;j< 10 ; j++){
        if(isSlimy(i, j)!= isSlimy2(i,j)){
             console.log("error");
        }
    }
}
```
no error was print.

**Comment by depressed-pho** [comment]
Wow... I'm still not sure if they are really the same, but as long as they produce the same result I'm happy to simplify it as you suggested. Thanks. I'll do that later.

**Comment by reedacartwright** [comment]
I can confirm that Bedrock Dedicated Server uses the above code to identify slime chunks. When you reverse engineer BDS using Ghidra it shows the above algorithm.

**Comment by hhhxiao** [comment]
> I can confirm that Bedrock Dedicated Server uses the above code to identify slime chunks. When you reverse engineer BDS using Ghidra it shows the above algorithm.

Thank you, recently I has also done some work on BDS,I think we have the same option.

**Comment by Artoria2e5** [comment]
For what is worth, I think you guys just bumped into a case of the magic constant-and-shift division algorithm. A tool for this stuff can be found at https://www.cse.scu.edu/~dlewis/book3/tools/DivideByConstant.shtml. For more explanation see https://ridiculousfish.com/blog/posts/labor-of-division-episode-iii.html.
